package com.afriland.diaspora.domain.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Vue détail d'un dossier — parité stricte avec le dict "application" retourné par
 * GET /api/backoffice/applications/{id} côté Python (app/routers/backoffice.py),
 * champs dans le même ordre d'insertion.
 */
public record ApplicationDetail(
        Long id,
        String reference,
        String lastName,
        String firstName,
        LocalDate birthDate,
        String birthPlace,
        String birthDepartment,
        String birthName,
        String residencyStatus,
        String addressLocation,
        String postalBox,
        String phone,
        String email,
        String contactPerson1Name,
        String contactPerson1Phone,
        String contactPerson2Name,
        String contactPerson2Phone,
        String fatherName,
        String motherName,
        String nationality,
        String residence,
        String sex,
        String maritalStatus,
        String matrimonialRegime,
        String identityDocumentNumber,
        LocalDate identityDocumentIssueDate,
        String identityDocumentIssuePlace,
        String rib,
        String incomeRange,
        String incomeCurrency,
        String activitySector,
        String activitySectorCode,
        String activitySubsector,
        String activitySubsectorCode,
        String accountObject,
        String accountObjectOther,
        String fundsOrigin,
        String fundsOriginOther,
        String accountType,
        String selectedPackageCode,
        String selectedPackageName,
        String selectedPackageCurrency,
        BigDecimal selectedPackageOpeningFee,
        BigDecimal selectedPackageSubscriptionFee,
        BigDecimal selectedPackageMonthlyFee,
        Boolean selectedPackagePaymentRequired,
        String preferredBranch,
        String accountPurpose,
        Boolean isPep,
        String pepDetails,
        String status,
        String clientMessage,
        String finalRib,
        String accountNumber,
        String riskLevel,
        Double kycScore,
        Double documentScore,
        String blackmoduleStatus,
        Double blackmoduleScore,
        String blackmoduleAlert,
        String reviewDecision,
        String reviewComment,
        String packagePaymentReference,
        String packagePaymentStatus,
        String packagePaymentProvider,
        BigDecimal packagePaymentAmount,
        String packagePaymentCurrency,
        String packagePaymentUrl) {
}
